# Generated by Django 3.2.25 on 2024-12-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredb', '0007_alter_friends_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
